export const GET_VENUE = 'GET_VENUE';
export const GET_VENUE_SUCCESS = 'GET_VENUE_SUCCESS';
export const GET_VENUE_FAILURE = 'GET_VENUE_FAILURE';
export const GET_VENUE_LIST = 'GET_VENUE_LIST';
export const GET_VENUE_LIST_SUCCESS = 'GET_VENUE_LIST_SUCCESS';
export const GET_VENUE_LIST_FAILURE = 'GET_VENUE_LIST_FAILURE';

// export const ADD_VENUE_EVENT = 'ADD_VENUE_EVENT';
// export const ADD_VENUE_EVENT_SUCCESS = 'ADD_VENUE_EVENT_SUCCESS';
// export const ADD_VENUE_EVENT_FAILURE = 'ADD_VENUE_EVENT_FAILURE';
// export const ADD_VENUE_REVIEW = 'ADD_VENUE_REVIEW';
// export const ADD_VENUE_REVIEW_SUCCESS = 'ADD_VENUE_REVIEW_SUCCESS';
// export const ADD_VENUE_REVIEW_FAILURE = 'ADD_VENUE_REVIEW_FAILURE';
// export const ADD_VENUE = 'ADD_VENUE';
// export const ADD_VENUE_SUCCESS = 'ADD_VENUE_SUCCESS';
// export const ADD_VENUE_FAILURE = 'ADD_VENUE_FAILURE';
// export const UPDATE_VENUE = 'UPDATE_VENUE';
// export const UPDATE_VENUE_SUCCESS = 'UPDATE_VENUE_SUCCESS';
// export const UPDATE_VENUE_FAILURE = 'UPDATE_VENUE_FAILURE';
// export const REMOVE_VENUE = 'REMOVE_VENUE';
// export const REMOVE_VENUE_SUCCESS = 'REMOVE_VENUE_SUCCESS';
// export const REMOVE_VENUE_FAILURE = 'REMOVE_VENUE_FAILURE';

//Here we import our action types as constants from our actions folder.
// import {
//   GET_VENUE, GET_VENUE_SUCCESS, GET_VENUE_FAILURE,
//   GET_VENUE_LIST, GET_VENUE_LIST_SUCCESS, GET_VENUE_LIST_FAILURE,
//   // ADD_VENUE, ADD_VENUE_FAILURE, ADD_VENUE_SUCCESS,
//   // ADD_VENUE_EVENT, ADD_VENUE_EVENT_FAILURE, ADD_VENUE_EVENT_SUCCESS,
//   // ADD_VENUE_REVIEW, ADD_VENUE_REVIEW_FAILURE, ADD_VENUE_REVIEW_SUCCESS,
//   // UPDATE_VENUE, UPDATE_VENUE_FAILURE, UPDATE_VENUE_SUCCESS,
//   // REMOVE_VENUE, REMOVE_VENUE_FAILURE, REMOVE_VENUE_SUCCESS,
