export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAILURE = 'GET_REVIEW_FAILURE';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

// export const REMOVE_REVIEW = 'REMOVE_REVIEW';
// export const REMOVE_REVIEW_SUCCESS = 'REMOVE_REVIEW_SUCCESS';
// export const REMOVE_REVIEW_FAILURE = 'REMOVE_REVIEW_FAILURE';

//Here we import our action types as constants from our actions folder.
// import {
//   GET_REVIEW, GET_REVIEW_SUCCESS, GET_REVIEW_FAILURE,
//   GET_REVIEW_LIST, GET_REVIEW_LIST_SUCCESS, GET_REVIEW_LIST_FAILURE,
//   // ADD_REVIEW, ADD_REVIEW_FAILURE, ADD_REVIEW_SUCCESS,
//   // ADD_REVIEW_EVENT, ADD_REVIEW_EVENT_FAILURE, ADD_REVIEW_EVENT_SUCCESS,
//   // ADD_REVIEW_REVIEW, ADD_REVIEW_REVIEW_FAILURE, ADD_REVIEW_REVIEW_SUCCESS,
//   // UPDATE_REVIEW, UPDATE_REVIEW_FAILURE, UPDATE_REVIEW_SUCCESS,
//   // REMOVE_REVIEW, REMOVE_REVIEW_FAILURE, REMOVE_REVIEW_SUCCESS,
