export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const ADD_USER_GROUP = 'ADD_USER_GROUP';
export const ADD_USER_GROUP_SUCCESS = 'ADD_USER_GROUP_SUCCESS';
export const ADD_USER_GROUP_FAILURE = 'ADD_USER_GROUP_FAILURE';

export const ADD_USER_REVIEW = 'ADD_USER_REVIEW';
export const ADD_USER_REVIEW_SUCCESS = 'ADD_USER_REVIEW_SUCCESS';
export const ADD_USER_REVIEW_FAILURE = 'ADD_USER_REVIEW_FAILURE';

export const ADD_USER_EVENT = 'ADD_USER_EVENT';
export const ADD_USER_EVENT_SUCCESS = 'ADD_USER_EVENT_SUCCESS';
export const ADD_USER_EVENT_FAILURE = 'ADD_USER_EVENT_FAILURE';

export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';
